#!/bin/bash -le

pacman -Syu --noconfirm base-devel git gmock gtest python meson fmt perl

# Needed to ensure PATH is properly set for perl, etc.
source /etc/profile

# build
meson setup build --prefix=/usr --buildtype=debugoptimized
meson compile -C build

# test
meson test -C build

# package
meson install -C build
