#!/bin/bash -le

cd /github/workspace

pacman -Syu --noconfirm base-devel git gmock gtest python meson fmt perl

# Needed to ensure PATH is properly set for perl, etc.
source /etc/profile

# build
meson build-asan --prefix=/usr --buildtype=debugoptimized -Db_sanitize=address
ninja -C build-asan

# test
meson test -C build-asan
