#!/bin/bash -le

pacman -Syu --noconfirm base-devel git gmock gtest python meson perl

# Needed to ensure PATH is properly set for perl, etc.
source /etc/profile

# build
meson setup build-asan --prefix=/usr --buildtype=debugoptimized -Db_sanitize=address
meson compile -C build-asan

# test
meson test -C build-asan
