#!/bin/bash -le

cd /github/workspace

# Needed to ensure PATH is properly set for perl, etc.
source /etc/profile

pacman -Syu --noconfirm base-devel git gmock gtest python cmake fmt

# build
mkdir -p build-san
cd build-san
cmake -DCMAKE_BUILD_TYPE=RelDebug -DENABLE_SANITIZERS=True ..
make test
