#!/bin/bash

set -e

tmpdir=$(mktemp -d)
trap 'rm -r "$tmpdir"' EXIT

if [[ ! -d .git ]]; then
  echo 'error: this script must be run from the repo root' >&2
  exit 1
fi

if [[ ! -f build/compile_commands.json ]]; then
  echo 'error: build/compile_commands.json not found' >&2
  exit 1
fi

sed 's/-pipe //' build/compile_commands.json >"$tmpdir"/compile_commands.json

git ls-files -z -- '*.cc' | xargs -0 clang-tidy -p "$tmpdir"
