#!/bin/bash

find_build_directory() {
  local f build_dirs=("$PWD"/.ninja_log "$PWD"/*/.ninja_log)

  for f in "${build_dirs[@]}"; do
    if [[ -e $f ]]; then
      printf '%s\n' "${f%/*}"
      return 0
    fi
  done

  echo "error: No build directory found. Have you run 'meson build' yet?" >&2
  return 1
}

assert_directory_exists() {
  if [[ ! -d $1 ]]; then
    printf 'FAIL: expected "%s", but not found\n' "$1" >&2
    exit 1
  fi
}

assert_file_exists() {
  if [[ ! -f $1 ]]; then
    printf 'FAIL: expected "%s", but not found\n' "$1" >&2
    exit 1
  fi
}

auracle() {
  "$AURACLE_BIN" -C "$TEST_TMPDIR" "$@" 2>/dev/null
}

BUILD_DIR=$(find_build_directory) || exit 1
AURACLE_BIN=$BUILD_DIR/auracle

TEST_TMPDIR=$(mktemp -d)
trap 'rm -rf "$TEST_TMPDIR"' EXIT

