#!/bin/bash

# shellcheck disable=SC1090
source "${0%/*}/common"

if ! auracle download pkgfile-git; then
  echo "FAIL: expected 0 exit status, got non-zero" >&2
  exit 1
fi
assert_file_exists "$TEST_TMPDIR/pkgfile-git/PKGBUILD"

if ! auracle download -r auracle-git; then
  echo "FAIL: expected 0 exit status, got non-zero" >&2
  exit 1
fi
assert_file_exists "$TEST_TMPDIR/auracle-git/PKGBUILD"
assert_file_exists "$TEST_TMPDIR/nlohmann-json/PKGBUILD"
