#!/bin/bash

# shellcheck disable=SC1090
source "${0%/*}/common"

if ! out=$(auracle rawsearch aura | jq .resultcount 2>&1) && (( out > 0 )); then
  echo "FAIL: expected valid JSON, but got: $out" >&2
  exit 1
fi

if ! out=$(auracle rawsearch auracle-git | jq .resultcount 2>&1) || (( out != 1 )); then
  echo "FAIL: expected valid JSON with resultcount of 1, but got: $out" >&2
  exit 1
fi

if ! out=$(auracle rawsearch --searchby maintainer falconindy | jq -r '.results[].Name') ||
    [[ $out != *auracle-git* ]]; then
  echo "FAIL: expected valid JSON with at least 'auracle-git', but got: $out" >&2
  exit 1
fi
