name: arch.x86_64
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    container:
      image: archlinux

    steps:
      - uses: actions/checkout@v4
      - run: build-aux/ci-test plain

  # ASAN tests don't work with abseil when it's linked as a shared lib.
  # test_asan:
  #   runs-on: ubuntu-latest

  #   container:
  #     image: archlinux

  #   steps:
  #     - uses: actions/checkout@v4
  #     - run: build-aux/ci-test asan
